language: node_js
node_js:
- '4.0'
- '9.0'
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    skip_cleanup: true
    email: tituswormer@gmail.com
    api_key:
      secure: eNmzV4MF+8Edjy5jnc4rIxCgSqiBs8QYtExugQyJEL71QYJANWT8p5Z5R5BHNRtqd6uDNrlKY9yRarwehYe941m5HP59plKvNS2+dpAiM+njnJcNLolMsPHdgq0TxhzVxgekRxGQ7E0Xfv1YZklqNGx6+Aa1tsM8JZSbuLTRerhbRFixVkhzKFlarVnGkSH6kaSqZc5g62NVbbgVsdKK7ElJesOk1O03d4/K1t9lP1dtnfFyYcZCiQXHro5fqtkHlCn56WkDgdcEel96FJfiWtYQ0zQ8UJXwjI5fHnCQIWBnYzkEzXUV8KY4/ztvzd+DgDSBUqA0kkoMbntAqfw9XiXBHV3ordK1b0Dpw5u06NF2OCfaNSnQQawK8ME5PNz5lsvzaMl2fd6jj8bn+k8WPjcW28W9pTqBVJZFtk6j9N5aoQKT6vw0Kc7ABfkSSpQwFcng3XB8BRnaQcp4IdHNlBnKDdGsG5G5ZrAHPpnipXhbiPOwbPc364+QvNgn71mm250Th7lV/f8eNhlIi5shR1OQlrz5qZrN9XCSYwyusk1CALAZSUZsUnK6AE0fDQXRSlCJaJNuInFktFEWtupoGn4jM/f+IWfciOUaltTFfbTV0+3l8cxHuVCIjd/FVF6FpGVWqXznqQIvJn2EXIS8hhDpcMYq7KFvJhuJqzFBHrs=
    on:
      tags: true
      node: '9.0'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: A6iWSrj79pFIfJyui0tKjiiUUDkU9yIbTq2QA0lD2gJKa9LH15V7MNeHdt8/TeLh4UN9WMik9AQslNq6gCePB3OFn1UQ38Od7o6JQGpxofbXIm3l7dSRu1ZYlbo7hiWqgbuZYAGfICPZ0YvfMLBvNbVaxSmbJGuGme1AgYrzDTF+Hx54kQp+FI2PBvB//Rzm201dMxZOCFUz64P1TZIB7BSLHaMC2lYufVWffYyVrOqg6laVM5O6nfCwqf5Xj+af37wjre5s4bAQhU7o7gbGMN3LdD27J6GtjGjaa8X7ybd8GQGlcWu8+ICMEZDr9eVZsAskazc0wwkpMPz/DgTE8FFuh9MhgKnTgsk8ohKeYOvEiomQeqhngjGDiMbhxlC4o+B9T78RpNoOQin+irPfOnWnvHgiNac8pagwmArL+GnFNxkME9B8sbm22rsnVx2erxsqWZN8/Wr/Rj+v7q2NVhbS/YyzyT7psRuFP09/I/4Q4Zxex/fgz61+X3H9arD0/9RY0HjDy2/vIAqeYMQ9rxQf9BNgi1VbaGI7r7TcioZWWYZB1QzS4tTg/qvCxbcak8//O+VZX2SztFpBkEAbMKEAg3+aGlhm1G/mGELPGR7PlT47phXZxIegn2+MlPBHCHcAIc+/kXTLcy5vtRSYjwTKGPIZTjOMSxtGp065SGY=
    file:
      - "remark-strip-badges.js"
      - "remark-strip-badges.min.js"
    on:
      tags: true
      node: '9.0'
