language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SBeuKzFvFGvTy4+eMExQOT+WuhakHZb6vC1DCQbE63EMlkQUR7vW2tTTi73qHXoD+7Zg/swsl8o1fsVEato/jlcLzdnC401QlYbvmGe8ye1JewY5CHAHUHim3ZSkjIJ27AR1Xx6Y5ERnARPSa97d+A8aw0ssV+yuUdSN3aSjVvulQPH5ZU6J6wQeioEtkKZ1McltownKnfPQPNZzQtOi9QGhURR+3uGV2bc3Aw5SA2+9wBFrCpvVw7ZyFNcIAYX6HW0kLr7HivBj2APcjcFeapS1g1jUCbz19yGrVCBeAPP1M+7yOR9QdiWdEnx8lrVuMZk8vUmlqq+ooAq7aLVT8rJCxb4phcGoy2RyMXOq57r12P5n5DlXgyxelSzbT2tRJJa0GCO3x82TCwv8RvxmUrOC0udNVVLVv5uxh3ZKe6lUze41W7G1zi7scnpwZW+y4nigtstx6R8mzZPgKxIEGcBbhOh2u2LfO89t6Upo0bgqdf9tYIoXm7g2tlQCO1dU8MDJDM0SWQiqefeXOOWfNMhRAyTOrBDjPqo5CzYlN8phLVyOsvG1BnyFzQU+MyGhMxaBD2zRXUfIXkQFE9Kd0bOAloZt389KVUFYPetBFapykzr9kRfMkKJ843zRcNZMVlphPF1jKTNC/V1PcgHYSOSI7/E5NNI21iUTm4SUSMo=
  file:
    - 'remark-strip-badges.js'
    - 'remark-strip-badges.min.js'
  on:
    tags: true
